# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R  
sudo: required
cache: packages
r_check_args: '--as-cran'

r_binary_packages:
  - testthat
  - devtools
  - knitr
  - rmarkdown
  - roxygen2

matrix:
  include:
  - os: osx
    r:
      - release
      - devel  
  - os: linux
    r:
      - release
    r_packages:
      - covr
    after_success:
      - Rscript -e 'library(covr); codecov()'      
  - os: linux
    env:
      - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
    r:
      - devel
    r_check_args: '--as-cran --use-valgrind'      
    addons:
      apt:
        packages:
          - valgrind
      