language: R
sudo: required
cache: packages
r_check_args: "--as-cran"
r_binary_packages:
- testthat
- devtools
- knitr
- rmarkdown
- roxygen2
matrix:
  include:
  - os: osx
  - os: linux
    r_packages:
    - covr
    after_success:
    - Rscript -e 'library(covr); codecov()'
  - os: linux
    env:
      global:
        - GH_TOKEN='G1MClqBZ5WNoHVrHR42B7uastul6rnTs3+COoRI2G4169ovEWH1kN1BueQONCmcIJdzaLEPA51jfg/GwOFa/FCSXxvbgHkEqmIuf6xdiJpRqLiXEfuCaE88/QCtxWpQW6gST06p/5Ek3tliBkkWfXGgj9lTUzb1kGxWzZN/IRWkfR6yoUSTgDWYM3W9mM4LX4sJFXg1+QYukzqCEYuyag+WOECZoOx9JXFCUPHe5sz5QKPhKbVKLGrU7oou5e8VFcyrn5CFk1qT2ge5D57nGU+VuNRXNV24atHXQbumH9+8qeJ/DBNz1uB1MHMNEZhCH8pn2aJ0+DJVr8anxo42IL3tNNfr7m64LOzVTyKrtg/cEsSxcb1W/wefrxlKGzK+YWoWS3ezKrMS4w6vHm69pYp/JGpsNDJgyXTctx9KXdg9e24T9Rmv7k1YgNTsQq4UhkOdOq+9xzuPS30tjnrBiF7h/nMDhE6aaFY3zNW1Q03PRPbPv2NkLAdBBuuc1qLWpBFzZ1AwGTIMAfraEf1Vzx22B6estsQnI/7BK7lapF9gBdpJ2uWHdMp8PMSNL5f4cA0PhfecW+3rDNi9NtrgLHfYNJppayTxCIA+SkavcZktiEVoyuVN+NjV5FUcqAyQG5o1phdvAe6r8kq/MBdUcR3hINQC1AMKsomat4dj9kb8='
    before_install:
    - chmod 755 ./.push_gh_pages.sh
    after_success:
    - ./.push_gh_pages.sh
  - os: linux
    env:
    - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
    r_check_args: "--as-cran --use-valgrind"
    addons:
      apt:
        packages:
        - valgrind