# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
r_check_args: --as-cran
r_binary_packages:
  - testthat
  - devtools
  - knitr
  - rmarkdown
  - roxygen2
os:
  - linux
  - osx