# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel

env:
  - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
  
sudo: required
cache: packages
r_check_args: '--as-cran --use-valgrind'

r_binary_packages:
  - testthat
  - devtools
  - knitr
  - rmarkdown
  - roxygen2

os:
  - linux
  - osx

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'